apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
spec:
  generators:
    - git:
        repoURL: https://github.com/heckelmann/platform.git
        revision: HEAD
        files:
          - path: gitops/helm/**/config.yaml
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      sources:
      - repoURL: '{{ repoURL }}'
        targetRevision: '{{ targetRevision }}'
        chart: '{{ chart }}'
        helm:
          valueFiles:
          - gitops/helm/{{ path.basename }}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ namespace }}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true

