apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-07-10T11:56:53Z"
  labels:
    operated-prometheus: "true"
  name: prometheus-operated
  namespace: monitoring
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    name: k8s
    uid: 13197ec5-9a1d-4a61-a55a-c8628f3d8fc8
  resourceVersion: "2277"
  uid: 8c3548a5-730d-4183-92c8-70edc7b545a6
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app.kubernetes.io/name: prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
